import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { C4IacGeneratedModule, C4IacGeneratedSharedModule } from './generated/module';
import { C4IacValidationRegistry, C4IacValidator } from './c-4-iac-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type C4IacAddedServices = {
    validation: {
        C4IacValidator: C4IacValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type C4IacServices = LangiumServices & C4IacAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const C4IacModule: Module<C4IacServices, PartialLangiumServices & C4IacAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new C4IacValidationRegistry(services),
        C4IacValidator: () => new C4IacValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createC4IacServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    C4Iac: C4IacServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        C4IacGeneratedSharedModule
    );
    const C4Iac = inject(
        createDefaultModule({ shared }),
        C4IacGeneratedModule,
        C4IacModule
    );
    shared.ServiceRegistry.register(C4Iac);
    return { shared, C4Iac };
}
